# Generated by Django 4.0.6 on 2022-09-14 19:42

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_post_resumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sumario',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
