# Generated by Django 4.0.6 on 2022-09-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post_sumario_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manchete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_destaque', models.CharField(max_length=36)),
                ('descricao', models.CharField(max_length=36)),
            ],
        ),
    ]
