# Generated by Django 4.0.6 on 2022-09-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_manchete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manchete',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
    ]
