# Generated by Django 4.0.6 on 2022-09-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_manchete_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_inicial', models.CharField(max_length=40)),
                ('subtexto', models.CharField(max_length=45)),
            ],
        ),
    ]
